# Generated by Django 4.1.3 on 2022-12-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('marks12', models.FloatField()),
                ('course', models.CharField(max_length=40)),
                ('father', models.CharField(max_length=40)),
                ('mother', models.CharField(max_length=40)),
            ],
        ),
    ]
