# Generated by Django 4.1.3 on 2023-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='marksheet',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='marksheet2',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
