# Generated by Django 4.1.3 on 2023-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userinfo_marksheet_userinfo_marksheet2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='marksheet',
            field=models.FileField(default=None, upload_to='marksheet/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='marksheet2',
            field=models.FileField(default=None, upload_to='marksheet2/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.FileField(default=None, upload_to='photo/'),
        ),
    ]
