# Generated by Django 4.1.3 on 2023-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userinfo_filled_alter_userinfo_marksheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='marksheet',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='marksheet2',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
