# Generated by Django 4.1.3 on 2023-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userinfo_marksheet_alter_userinfo_marksheet2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='filled',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='marksheet/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='marksheet2',
            field=models.ImageField(blank=True, null=True, upload_to='marksheet2/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
