# Generated by Django 4.1.3 on 2023-01-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userinfo_filled_alter_userinfo_marksheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='filled',
        ),
    ]
